# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# [[social]]
#     identifier = "telegram"
#     name       = "Telegram"
#     url        = "https://t.me/ЮЗЕР"
# 
#     [social.params]
#         icon = "brand-telegram"

# [[social]]
#     identifier = "github"
#     name       = "GitHub"
#     url        = "https://github.com/ЮЗЕР/"
# 
#     [social.params]
#         icon = "brand-github"
